### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by gleyba** [blackhole89/macros#2]
I'd like to use this repo and maybe contribute, but I can't conform to GPLv3.
Could you support BSD also, or it is principle for you?

**Comment by blackhole89** [comment]
Sorry, I do want the preprocessor itself to be licensed under the GPL as a matter of principle; I am not sure I see any valid top-level reason to use a different license for the macro processor itself, which is not designed to be linked against or integrated in larger codebases. (Compare gcc)

I am, however, licensing the examples under the MIT license, and it is certainly not my intention that this tool can't be _used_ in a proprietary stack. If there are any changes I should do to the licensing to make this easier (while not enabling the possibility that someone takes the code, turns it into a product and sells it for money without making the code available), I would be grateful for suggestions.
